-- Table to store ticker metadata
CREATE TABLE prices.metadata (
    permaticker character varying PRIMARY KEY,
    ticker character varying,
    use_permaticker boolean,
    ticker_name character varying,
    exchange character varying,
    asset_type character varying,
    cap_category character varying DEFAULT 'unknown'::character varying,
    sector character varying DEFAULT 'unknown'::character varying,
    industry character varying DEFAULT 'unknown'::character varying,
    sic_sector character varying DEFAULT 'unknown'::character varying,
    sic_industry character varying DEFAULT 'unknown'::character varying,
    company_website character varying,
    is_active boolean,
    start_date date,
    end_date date,
    years_listed bigint,
    designation character varying,
    last_price_db_date date DEFAULT '1990-01-01'::date,
    last_statement_db_date date DEFAULT '1990-01-01'::date,
    last_statement_endpoint_update date,
    last_price_endpoint_update date,
    last_processed_date date DEFAULT '1990-01-01'::date,
    prices_initialized boolean DEFAULT false,
    fundamentals_initialized boolean DEFAULT false,
    etf_info_initialized boolean DEFAULT false,
    requires_backtest boolean DEFAULT false,
    table_alias character varying GENERATED ALWAYS AS (
        CASE
            WHEN (use_permaticker = false) THEN ticker
            ELSE permaticker
        END
    ) STORED,
    no_api_statements boolean DEFAULT false,
    next_expected_statements_release date GENERATED ALWAYS AS ((newest_db_statements + '3 mons'::interval)) STORED
);
-- Sample ticker price table
CREATE TABLE prices.aapl (
    date date PRIMARY KEY,
    open double precision,
    high double precision,
    low double precision,
    close double precision,
    volume bigint,
    split_factor double precision,
    market_cap double precision,
    enterprise_val double precision,
    pe_ratio double precision,
    pb_ratio double precision,
    trailing_peg_1y double precision
);
-- Sample ticker fundamental statement table
CREATE TABLE fundamentals.aapl_income_statement (
    date date PRIMARY KEY,
    consolidated_income double precision,
    cost_rev double precision,
    ebit double precision,
    ebitda double precision,
    ebt double precision,
    eps double precision,
    eps_dil double precision,
    gross_profit double precision,
    intexp double precision,
    net_inc_com_stock double precision,
    net_inc_disc_ops double precision,
    netinc double precision,
    non_controlling_interests double precision,
    opex double precision,
    opinc double precision,
    pref_d_v_ds double precision,
    revenue double precision,
    rnd double precision,
    sga double precision,
    shareswa double precision,
    shareswa_dil double precision,
    tax_exp double precision
);
-- Backtest success rate table
CREATE TABLE models.backtest_success_rates (
    date date,
    ticker character varying NOT NULL,
    sector character varying,
    cap character varying,
    exchange character varying,
    indicator character varying,
    signal_name character varying NOT NULL,
    reversal_count integer,
    reversal_success integer,
    reversal_failure integer,
    continuation_count integer,
    continuation_success integer,
    continuation_failure integer
);
ALTER TABLE ONLY models.backtest_success_rates
    ADD CONSTRAINT backtest_success_rates_pkey PRIMARY KEY (ticker, signal_name);
-- Sample parquet file schema as a DuckDB table
CREATE TABLE bac (
    date VARCHAR, 
    open DOUBLE, 
    high DOUBLE, 
    low DOUBLE, 
    "close" DOUBLE, 
    volume BIGINT, 
    split_factor DOUBLE, 
    market_cap DOUBLE, 
    enterprise_val DOUBLE, 
    pe_ratio DOUBLE, 
    pb_ratio DOUBLE, 
    trailing_peg_1y DOUBLE, 
    atr DOUBLE, 
    ema_5 DOUBLE, 
    ema_10 DOUBLE, 
    ema_20 DOUBLE, 
    ema_50 DOUBLE, 
    ema_100 DOUBLE, 
    ema_250 DOUBLE, 
    kalman_close DOUBLE, 
    kalman_trend DOUBLE, 
    close_percent_from_max DOUBLE, 
    close_percent_from_min DOUBLE, 
    demand_idx DOUBLE, 
    aroon DOUBLE, 
    cci DOUBLE, 
    cci_ma DOUBLE, 
    rsi DOUBLE, 
    stdev_percent_of_sma DOUBLE, 
    kst DOUBLE, 
    kst_sig DOUBLE, 
    bollinger_upper_band DOUBLE, 
    bollinger_sma DOUBLE, 
    bollinger_lower_band DOUBLE, 
    bollinger_band_range DOUBLE, 
    macd DOUBLE, macd_sig DOUBLE, 
    macd_hist DOUBLE, wpr DOUBLE, 
    stochastic_k DOUBLE, 
    stochastic_d DOUBLE, 
    psar DOUBLE, 
    adx DOUBLE, 
    dmi_plus DOUBLE, 
    dmi_minus DOUBLE, 
    kama DOUBLE, 
    obv DOUBLE, 
    two_week_trend_slope DOUBLE, 
    month_trend_slope DOUBLE, 
    three_month_trend_slope DOUBLE, 
    six_month_trend_slope DOUBLE, 
    year_trend_slope DOUBLE, 
    three_year_trend_slope DOUBLE, 
    two_week_trend BIGINT, 
    month_trend BIGINT, 
    three_month_trend BIGINT, 
    six_month_trend BIGINT, 
    year_trend BIGINT, 
    three_year_trend BIGINT, 
    trend_score DOUBLE, 
    daily_price_change DOUBLE, 
    daily_price_ceiling DOUBLE, 
    daily_price_floor DOUBLE, 
    reversal_conf VARCHAR, 
    trend_reversal_type VARCHAR, 
    trend_reversal_threshold DOUBLE, 
    current_trend BIGINT, 
    trend_confidence_factor DOUBLE, 
    bullish_demand_idx_threshold_ind DOUBLE, 
    bullish_demand_idx_cross_zero_ind DOUBLE, 
    bullish_demand_idx_longterm_divergence_ind DOUBLE, 
    bullish_demand_idx_trend_divergence_ind DOUBLE, 
    bearish_demand_idx_trend_divergence_ind DOUBLE, 
    bearish_demand_idx_cross_zero_ind DOUBLE, 
    bearish_demand_idx_longterm_divergence_ind DOUBLE, 
    bullish_wpr_divergence_ind DOUBLE, 
    bullish_wpr_3_period_threshold_ind DOUBLE, 
    bearish_wpr_divergence_ind DOUBLE, 
    bearish_wpr_3_period_threshold_ind DOUBLE, 
    bullish_macd_price_divergence_ind DOUBLE, 
    bullish_macd_crossover_sigline_ind DOUBLE, 
    bullish_macd_5_period_low_ind DOUBLE, 
    bullish_macd_cross_above_zero_ind DOUBLE, 
    bearish_macd_price_divergence_ind DOUBLE, 
    bearish_macd_crossover_sigline_ind DOUBLE, 
    bearish_macd_5_period_high_ind DOUBLE, 
    bearish_macd_cross_below_zero_ind DOUBLE, 
    bullish_cci_trend_reversal_ind DOUBLE, 
    bullish_cci_divergence_ind DOUBLE, 
    bearish_cci_trend_reversal_ind DOUBLE, 
    bearish_cci_divergence_ind DOUBLE, 
    bullish_rsi_divergence_ind DOUBLE, 
    bullish_rsi_failure_swing_ind DOUBLE, 
    bullish_rsi_threshold_ind DOUBLE, 
    bearish_rsi_divergence_ind DOUBLE, 
    bearish_rsi_failure_swing_ind DOUBLE, 
    bearish_rsi_threshold_ind DOUBLE, 
    bullish_bollinger_squeeze_ind DOUBLE, 
    bullish_bollinger_threshold_ind DOUBLE, 
    bearish_bollinger_squeeze_ind DOUBLE, 
    bearish_bollinger_threshold_ind DOUBLE, 
    bullish_kst_crossover_sigline_ind DOUBLE, 
    bullish_kst_cross_above_zero_ind DOUBLE, 
    bearish_kst_crossover_sigline_ind DOUBLE, 
    bearish_kst_cross_below_zero_ind DOUBLE, 
    bullish_stochastic_crossover_d_ind DOUBLE, 
    bullish_stochastic_price_divergence_ind DOUBLE, 
    bearish_stochastic_crossover_d_ind DOUBLE, 
    bearish_stochastic_price_divergence_ind DOUBLE, 
    bullish_adx_threshold_crossover_ind DOUBLE, 
    bullish_adx_trend_after_low_ind DOUBLE, 
    bearish_adx_threshold_crossover_ind DOUBLE, 
    bearish_adx_trend_after_high_ind DOUBLE, 
    bullish_psar_below_close_ind DOUBLE, 
    bearish_psar_above_close_ind DOUBLE, 
    bullish_breakaway_ind DOUBLE, 
    bullish_ladder_ind DOUBLE, 
    bearish_breakaway_ind DOUBLE, 
    bearish_ladder_ind DOUBLE, 
    bullish_stick_sandwich_ind DOUBLE, 
    bullish_unique_three_rivers_ind DOUBLE, 
    bullish_morning_star_ind DOUBLE, 
    bullish_tri_star_ind DOUBLE, 
    bullish_three_white_soldiers_ind DOUBLE, 
    bearish_three_black_crows_ind DOUBLE, 
    bearish_evening_star_ind DOUBLE, 
    bearish_tri_star_ind DOUBLE, 
    bullish_engulfing_ind DOUBLE, 
    bullish_meeting_lines_ind DOUBLE, 
    bullish_harami_ind DOUBLE, 
    bullish_harami_cross_ind DOUBLE, 
    bullish_piercing_line_ind DOUBLE, 
    bullish_kicking_ind DOUBLE, 
    bullish_homing_pigeon_ind DOUBLE, 
    bullish_matching_low_ind DOUBLE, 
    bullish_doji_star_ind DOUBLE, 
    bearish_shooting_star_ind DOUBLE, 
    bearish_engulfing_ind DOUBLE, 
    bearish_meeting_lines_ind DOUBLE, 
    bearish_harami_ind DOUBLE, 
    bearish_harami_cross_ind DOUBLE, 
    bearish_dark_cloud_cover_ind DOUBLE, 
    bearish_kicking_ind DOUBLE, 
    bearish_matching_high_ind DOUBLE, 
    bullish_belt_hold_ind DOUBLE, 
    bullish_inverted_hammer_ind DOUBLE, 
    bullish_hammer_ind DOUBLE, 
    bearish_belt_hold_ind DOUBLE, 
    bearish_hanging_man_ind DOUBLE, 
    total_score DOUBLE, 
    cap VARCHAR, 
    exchange VARCHAR, 
    sector VARCHAR, 
    ticker VARCHAR
);

